# @hostname = https://localhost:443
@hostname = http://localhost:80

### запрос на Retrieve C(R)UD
GET {{hostname}}/api/cameras

###

### запрос на Retrieve C(R)UD
GET {{hostname}}/api/cameras/14
Content-Type: application/json

### запрос на Create (C)RUD
POST {{hostname}}/api/cameras
Content-Type: application/json

{
  "brand": "Leica",
  "release_year": 2026,
  "megapixels": "50.2",
  "sensor_type": "Full_Frame",
  "interchangeable_lens": true,
  "price": 900000
}

#TODO запросы DELETE и PATCH

### запрос на Delete CRU(D)
DELETE {{hostname}}/api/cameras/4


### запрос на Update CR(U)D

PUT {{hostname}}/api/cameras/100
Content-Type: application/json

{
  "brand": "Nikon",
  "release_year": 2020,
  "megapixels": "20.4",
  "sensor_type": "Full_Frame",
  "interchangeable_lens": true,
  "price": 900000
}

###

PATCH {{hostname}}/api/cameras/23
Content-Type: application/json

{
  "price": 120000
}