# Generated by Django 6.0.3 on 2026-04-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('megapixels', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sensor_type', models.CharField(max_length=20)),
                ('interchangeable_lens', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
