services:

  postgres-service:
    build: ./postgres
    env_file: .env
    # включаю ssl, указываю путь к сертификату, приватному ключу и путь к конфигу
    command: >
      postgres
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c hba_file=/var/lib/postgresql/pg_hba.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # проверка что БД готова принимать запросы
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate-service:
    build: ./backend
    env_file: .env # нужен чтобы подключиться к БД
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput"
    volumes:
      - static_files:/staticfiles
      - ./postgres/certs/root.crt:/ssl_certs/root.crt:ro
    depends_on:
      postgres-service:
        # ждать пока postgres пройдёт healthcheck
        condition: service_healthy

  backend-service:
    build: ./backend
    env_file: .env
    command: gunicorn lab1.wsgi:application --bind 0.0.0.0:8000 # слушать на всех интерфейсах внутри контейнера
    volumes:
      - static_files:/staticfiles
      - ./postgres/certs/root.crt:/ssl_certs/root.crt:ro
    depends_on:
      migrate-service:
        # ждать пока миграции успешно завершатся
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "manage.py", "health_check", "health-check", "--no-http"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  nginx-service:
    build: ./nginx
    ports:
    # хост : контейнер
      - "80:80"
      - "443:443"
    volumes:
      - static_files:/static
    depends_on:
      backend-service:
        # ждать пока backend пройдёт healthcheck
        condition: service_healthy

volumes:
  postgres_data: # данные БД 
  static_files:

# сгенерировать данные в бд
# docker compose exec backend-service python manage.py shell -c "from mainapp.gentestdata import gentestdata; gentestdata()"